#!/bin/bash

#
# A tool for properly starting and tuning a Minecraft server under the better performant
# OpenJ9 (https://www.eclipse.org/openj9) JVM. The main advantage of OpenJ9 is that it
# will be able to use less memory and provide a much better performance.
#
# This script is initially intended to be used in development environment, but with some
# modifications in the environment variables it can be used in production as well. This
# can also work with Velocity out of the box just by changing the jar filename.
#
# This script is adapted/modified from the original script made by Astei:
# https://steinborn.me/posts/tuning-minecraft-openj9/
#
# Copyright (C) 2022 Hexalite Network
# This script is licensed under the MIT license.
#
### Configuration
### The following variables can be changed to fit your needs.

# Heap Size: The size of the heap in megabytes that you plan to
#            allocate to the JVM. By default, the heap size is set
#            to 1024 (equivalent to 1 gigabyte).
HEAP_SIZE=${HEAP_SIZE:-1024}

# Server Filename: The name of the jar file that the Purpur server is located.
#                  By default, the jar file is assumed to be in the current
#                  directory with the name "purpur.jar".
SERVER_FILENAME=${SERVER_FILENAME:-purpur.jar}

# Minimum nursery size: The minimum size of the nursery in megabytes that
#                      you plan to allocate to the JVM. By default, the
#                      nursery size is set to the heap size divided by 4.
MIN_NURSERY_SIZE=${MIN_NURSERY_SIZE:-$((HEAP_SIZE / 4))}

# Maximum nursery size: The maximum size of the nursery in megabytes that
#                      you plan to allocate to the JVM. By default, the
#                      nursery size is set to the heap size multiplied by 2
#                      then divided by 5.
MAX_NURSERY_SIZE=${MAX_NURSERY_SIZE:-$((HEAP_SIZE * 2 / 5))}

# Additional JVM flags: Additional flags that you want to pass to the JVM.
#                      By default, there is only a few flags set to optimize
#                      the Minecraft server.
ADDITIONAL_JVM_FLAGS=${ADDITIONAL_JVM_FLAGS:-"-Xgcpolicy:balanced -Xdisableexplicitgc"}
                                             # For Minecraft 1.12.2 and below (or if you are using Velocity), "-Xgcpolicy:gencon" is recommend
                                             # If you are using a VPS or dedicated server, adding "-Xtune:virtualized" is recommended

# Additional arguments: Additional arguments that you want to pass to the
#                      Minecraft server. By default, only the "nogui" argument
#                      is set to disable the server GUI.
ADDITIONAL_ARGUMENTS=${ADDITIONAL_ARGUMENTS:-"nogui"}

# Java binary: The path to the Java binary that you want to use. By default,
#              the Java binary is assumed to be located at `which java`.
JAVA_BINARY=${JAVA_BINARY:-`which java`}


# Finally, we can start the server. This is not really necessary to modify if you want
# to use this script in production. You can just modify the above variables or just pass
# other ones exporting it in your shell environment.
DIRNAME=`dirname "$(realpath "$0")"`
(cd "$DIRNAME" && "$JAVA_BINARY" -Xms${HEAP_SIZE}M -Xmx${HEAP_SIZE}M -Xmns${MIN_NURSERY_SIZE} -Xmnx${MAX_NURSERY_SIZE} $ADDITIONAL_JVM_FLAGS -jar $SERVER_FILENAME $ADDITIONAL_ARGUMENTS)